name: CI
on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'
jobs:
  build-test:
    name: Build and test on Erlang/OTP ${{ matrix.otp-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp-version: [23, 24]
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp-version}}
          elixir-version: 1.11.4
      - name: Compile
        run: make
      - name: Test
        run: make tests
